--CREATE TABLE Produto (
--                codigo INT IDENTITY NOT NULL,
--                descricao VARCHAR(80) NOT NULL,
--                unidade_medida VARCHAR(60) NOT NULL,
--                data_vencimento DATE NOT NULL,
--                CONSTRAINT codigo PRIMARY KEY (codigo)
--)
--
